import type { Database } from '@/lib/types/database.types'

export const DEFAULT_TASKS: Database['public']['Tables']['task']['Insert'][] = [
    {
        title: 'Basecoat the squad',
        game: 'Starter Set',
        mfg: null,
        estimated_minutes_min: 30,
        estimated_minutes_max: 60,
        priority: 3,
        required_tools_tags: ['round brush', 'flat brush'],
        skills_tags: ['basecoating', 'layering'],
        status: 'backlog',
    },
    {
        title: 'Wash and shade pass',
        game: 'Starter Set',
        mfg: null,
        estimated_minutes_min: 20,
        estimated_minutes_max: 45,
        priority: 2,
        required_tools_tags: ['round brush'],
        skills_tags: ['washing'],
        status: 'backlog',
    },
    {
        title: 'Highlight armor edges',
        game: 'Starter Set',
        mfg: null,
        estimated_minutes_min: 25,
        estimated_minutes_max: 60,
        priority: 4,
        required_tools_tags: ['highlight brush', 'detail brush'],
        skills_tags: ['highlighting', 'blending'],
        status: 'backlog',
    },
    {
        title: 'Basing pass',
        game: 'Starter Set',
        mfg: null,
        estimated_minutes_min: 30,
        estimated_minutes_max: 90,
        priority: 2,
        required_tools_tags: ['drybrush'],
        skills_tags: ['basing', 'drybrushing'],
        status: 'backlog',
    },
    {
        title: 'Glaze and smooth transitions',
        game: 'Starter Set',
        mfg: null,
        estimated_minutes_min: 30,
        estimated_minutes_max: 75,
        priority: 3,
        required_tools_tags: ['round brush'],
        skills_tags: ['glazing', 'blending'],
        status: 'backlog',
    },
]
